apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-server
  name: oauth-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauth-server
  strategy: {}
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      containers:
        - image: brewery/oauth-server:1.8.0
          name: oauth-server
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db-host
                  name: oauth-server-secrets-stage
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: oauth-server-secrets-stage
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: oauth-server-secrets-stage
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: oauth-server-secrets-stage
            - name: AUTHORIZATION_CODE_EXPIRES_MS
              value: "300000"
            - name: COOKIE_ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  key: cookie-encryption-secret
                  name: oauth-server-secrets-stage
            - name: COOKIE_ENCRYPTION_ALGORITHM
              value: "AES"
            - name: LOGIN_SIGNUP_ENDPOINT
              value: "https://auth.stage.id.realityos.one/signin"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt-secret-key
                  name: oauth-server-secrets-stage
            - name: ENABLE_SWAGGER
              value: "false"
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: acr-secret
status: {}
