apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-server
  name: oauth-server
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: oauth-server