version: '3.8'
services:
  oauth-server-server:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_HOST: oauth-server-postgres:5432
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: postgres
      COOKIE_ENCRYPTION_ALGORITHM: ${COOKIE_ENCRYPTION_ALGORITHM}
      COOKIE_ENCRYPTION_SECRET: ${COOKIE_ENCRYPTION_SECRET}
      LOGIN_SIGNUP_ENDPOINT: ${LOGIN_SIGNUP_ENDPOINT}
      AUTHORIZATION_CODE_EXPIRES_MS: ${AUTHORIZATION_CODE_EXPIRES_MS}
      ENABLE_SWAGGER: ${ENABLE_SWAGGER}
    depends_on:
      - oauth-server-postgres

  oauth-server-postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgrespassword
