name: Release to Docker Hub

on:
  push:
    branches:
      - 'release/**'

jobs:
  release:
    name: Release to Production
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Set Release Version
        run: |
          BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}
          RELEASE_VERSION=${BRANCH_NAME/release\/v/}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          mvn -B versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false
          git add pom.xml

      - name: Run Tests
        run: mvn test

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Set version to $RELEASE_VERSION [skip ci]"
          branch: ${{ steps.branch-name.outputs.current_branch }}

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: brewery/oauth-server:latest, brewery/oauth-server:${{ env.RELEASE_VERSION }}
          platforms: linux/amd64,linux/arm64

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create PR to main
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: Auto Merge PR
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge

      - name: Auto Approve PR
        if: steps.open-pr.outputs.pr_created == 'true'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.open-pr.outputs.pr_number }}
