name: Docker Image CI

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    
    - name: Set Release Version
      id: releaseversion
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_VERSION=${RELEASE_VERSION/release\/v/}" >> $GITHUB_OUTPUT
        mvn -B versions:set -DnewVersion=$RELEASE_VERSION
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

#    - name: Set up Docker QEMU
#      uses: docker/setup-qemu-action@v2
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: brewery/oauth-server:latest, brewery/oauth-server:${{ steps.releaseversion.outputs.RELEASE_VERSION }}
          platforms: linux/amd64,linux/arm64
