on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    types: [ opened, synchronize, reopened ]
name: Sonar Analyze
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
        with:
          checkout-fetch-depth: 0
          java-version: 19
          maven-version: 3.9.0
          java-distribution: "temurin"

      - name: Sonar Analyze
        run: mvn verify sonar:sonar -Pcoverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
