on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
name: Sonar Analyze
jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.6.3', '3.8.7', '3.9.0' ]

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 19
          maven-version: ${{ matrix.maven }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Sonar Analyze
        run: mvn install sonar:sonar -Pcoverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
